apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
  labels:
    app: nginx
data:
  APP_MODE: "dev"
  APP_ENV: "development"
  LOG_LEVEL: "info"
  MAX_CONNECTIONS: "100"
  NGINX_WORKER_PROCESSES: "2"
