apiVersion: v1
kind: Service
metadata:
  name: frontend-dev
  namespace: simple-chat-dev
  labels:
    app: frontend
    environment: development
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 5173
    protocol: TCP
    name: http
  selector:
    app: frontend
    environment: development
