apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-stage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mdarifahammedreza/simpleChatserver.git
    targetRevision: stage
    path: k8s/stage
  destination:
    server: https://kubernetes.default.svc
    namespace: simple-chat-stage
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
